week_6/day_4/jeremys_hotel_reviewer/config/routes.rb
Rails.application.routes.draw do

  root 'hotels#index'

  resources :hotels do
    resources :reviews
  end

end

week_6/day_4/jeremys_hotel_reviewer/app/models/hotel.rb
class Hotel < ActiveRecord::Base
  has_many :reviews

  validates :name, presence: true
  validates :city, presence: true
  validates :country, presence: true

  def average_rating
    return 'No ratings yet!' if reviews.none?
    
    # ratings = []
    # self.reviews.each { |review| ratings << review.rating }
    # ratings.sum / ratings.size
    
    self.reviews.map(&:rating).inject(:+) / reviews.size
  end

end

week_6/day_4/jeremys_hotel_reviewer/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :hotel
end

week_6/day_4/jeremys_hotel_reviewer/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController

  def index
    @hotels = Hotel.all
  end

  def new
    @hotel = Hotel.new
  end

  def create
    hotel = Hotel.new params[:hotel].permit(:name, :city, :country)

    if hotel.save
      redirect_to hotels_path
    else
      render 'new'
    end
  end

  def show
    @hotel = Hotel.find(params[:id])
  end

end

week_6/day_4/jeremys_hotel_reviewer/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @hotel = Hotel.find(params[:hotel_id])
  end

  def create
    hotel = Hotel.find(params[:hotel_id])
    hotel.reviews << Review.create(params[:review].permit(:description, :rating))
    
    redirect_to hotel
  end
end

week_6/day_4/jeremys_hotel_reviewer/app/helpers/hotels_helper.rb
module HotelsHelper
end

week_6/day_4/jeremys_hotel_reviewer/app/helpers/reviews_helper.rb
module ReviewsHelper
end

week_6/day_4/jeremys_hotel_reviewer/app/views/hotels/index.html.erb
<%= link_to 'Add a hotel', new_hotel_path %>

<% @hotels.each do |hotel| %>
  <p><%= link_to hotel.name, hotel_path(hotel) %></p>
<% end %>

week_6/day_4/jeremys_hotel_reviewer/app/views/hotels/new.html.erb
<%= form_for @hotel do |form| %>
  
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :city %>
  <%= form.text_field :city %>

  <%= form.label :country %>
  <%= form.text_field :country %>

  <%= form.submit 'Submit' %>

<% end %>

week_6/day_4/jeremys_hotel_reviewer/app/views/hotels/show.html.erb
<h1><%= @hotel.name %></h1>

<%= link_to 'Add review', new_hotel_review_path(@hotel) %>




<% @hotel.reviews.each do |review| %>
  <p>review was created <%= time_ago_in_words(review.created_at) %> ago</p>
  <p><%= review.description %></p>
<% end %>