week_6/day_2/planets_app/config/routes.rb
Rails.application.routes.draw do

  resources :planets

end

week_6/day_2/planets_app/app/models/planet.rb
class Planet < ActiveRecord::Base

end

week_6/day_2/planets_app/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController

  def index
    # using active record to pull all of the planets out of the database and storing them in an instance variable
    @planets = Planet.all
  end

  def show
    # this will look up the planet in the database using its id from params 
    @planet = Planet.find(params[:id])
  end

  def new
    # instantiate an empty planet object
    @planet = Planet.new
  end

  def create
    Planet.create(planet_params)
    redirect_to(planets_path)
  end

  def destroy
    planet = Planet.find(params[:id])
    planet.destroy
    redirect_to(planets_path)
  end

  def edit
    @planet = Planet.find(params[:id])
  end

  def update
    # look up the planet in the database
    @planet = Planet.find(params[:id])
    # update the attributes
    @planet.update(planet_params)
    redirect_to(planets_path)
  end

  private
  # this is a security method that allows us to update the following columns in the database at the same time
  def planet_params
    params.require(:planet).permit(:name, :image, :mass, :moons)
  end


end

week_6/day_2/planets_app/app/views/planets/edit.html.erb
<%= form_for @planet do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.label :mass %>
  <%= f.text_field :mass %>

  <%= f.label :moons %>
  <%= f.text_field :moons %>

  <%= f.submit 'Update planet!' %>

<% end %>

week_6/day_2/planets_app/app/views/planets/index.html.erb
<h1>Index Page</h1>

<div class="list-group">
  <% @planets.each do |planet| %>
    <div class="list-group-item">
      <ul class="planet">
        <li><%= link_to(planet.name, planet_path(planet.id)) %></li>
        <li><%= link_to('DELETE', planet_path(planet.id), method: :delete) %></li>
        <li><%= link_to('EDIT', edit_planet_path(planet.id))%></li>
      </ul>
    </div>
  <% end %>
</div>

week_6/day_2/planets_app/app/views/planets/new.html.erb
<%= form_for @planet do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :image %>
  <%= f.text_field :image %>

  <%= f.label :mass %>
  <%= f.text_field :mass %>

  <%= f.label :moons %>
  <%= f.text_field :moons %>

  <%= f.submit 'Create planet!' %>

<% end %>

week_6/day_2/planets_app/app/views/planets/show.html.erb
<h1>testing</h1>

<div class="planet-info">
  <h3><%= @planet.name %></h3>
  <%= image_tag(@planet.image, width: 200) %>
</div>